### ISSUE TITLE
cc-cell组件left-icon插槽有bug

### ISSUE THREAD

**Issue by King-Love** [LadyChatterleyLover/cc-ui#2]
当前逻辑
`<view v-if="icon" class="cc-cell-left-icon">
          <cc-icon :size="iconSize" :type="icon" color="#323233"></cc-icon>
          <slot name="left-icon"></slot>
</view>`
我调整后的逻辑
`<view v-if="icon" class="cc-cell-left-icon">
          <cc-icon :size="iconSize" :type="icon" color="#323233"></cc-icon>
</view>
<view v-else class="cc-cell-left-icon">
	<slot name="left-icon"></slot>
</view>`

**Comment by LadyChatterleyLover** [comment]
已修复, 谢谢, 下次可以直接pr哈
